/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CartaoRouteImport } from './routes/cartao'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ExtratoRouteImport } from './routes/extrato'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as LoginRouteImport } from './routes/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaoRoute = CartaoRouteImport.update({
  id: '/cartao',
  path: '/cartao',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratoRoute = ExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cartao': typeof CartaoRoute
  '/categorias': typeof CategoriasRoute
  '/contas': typeof ContasRoute
  '/extrato': typeof ExtratoRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cartao': typeof CartaoRoute
  '/categorias': typeof CategoriasRoute
  '/contas': typeof ContasRoute
  '/extrato': typeof ExtratoRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cartao': typeof CartaoRoute
  '/categorias': typeof CategoriasRoute
  '/contas': typeof ContasRoute
  '/extrato': typeof ExtratoRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/cartao'
    | '/categorias'
    | '/contas'
    | '/extrato'
    | '/importar'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/cartao'
    | '/categorias'
    | '/contas'
    | '/extrato'
    | '/importar'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/cartao'
    | '/categorias'
    | '/contas'
    | '/extrato'
    | '/importar'
    | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CartaoRoute: typeof CartaoRoute
  CategoriasRoute: typeof CategoriasRoute
  ContasRoute: typeof ContasRoute
  ExtratoRoute: typeof ExtratoRoute
  ImportarRoute: typeof ImportarRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartao': {
      id: '/cartao'
      path: '/cartao'
      fullPath: '/cartao'
      preLoaderRoute: typeof CartaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrato': {
      id: '/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof ExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CartaoRoute: CartaoRoute,
  CategoriasRoute: CategoriasRoute,
  ContasRoute: ContasRoute,
  ExtratoRoute: ExtratoRoute,
  ImportarRoute: ImportarRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
